### ISSUE TITLE
Scripts finales (sin bonus)

### ISSUE THREAD

**Issue by ralvarez-hub** [ralvarez-hub/decont#1]
Hola Tomás:
he subido los scripts finales, aunque aún me faltan los bonus, que intentaré hacerlos también.
Como ves, me ha costado tiempo, pero en mi defensa diré que la mayor parte del tiempo me tuvieron atascada dos tonterías tan grandes que cuando las resolví no me lo podía creer. Una, no darme cuenta de que la "P" de la pista que diste para el wget era mayúscula (como está en un botoncito, me pareció pequeña, no me di cuenta). Y la otra, en el script download.sh, no conseguía que me funcionase lo del "yes" opcional para descomprimir, hasta que me di cuenta de que lo que me fallaba era que faltaban los espacios al lado de los corchetes del if. En fin.
Me ha servido mucho para ir aprendiendo a leer e interpretar los errores que da.
En cualquier caso, creo que ahora funciona todo perfecto, sin ningún error. Si puedes decirme si tú ves algo que yo no vea? (ya para el lunes, eh? el fin de semana no se trabaja)
Ahora voy a ponerme con los bonus, a ver si lo consigo a tiempo.
Gracias!
Ruth

**Comment by tdido** [comment]
Hola Ruth.

Esto está fenomenal, funciona perfectamente. Muy buen trabajo. Y en cuanto al tiempo, por eso había comentado que no lo iba a tener en cuenta: me parece que el proceso que hiciste de ir descubriendo las cosas por tu cuenta es la mejor manera de aprender.

Te dejo tres comentarios, pero sólo para que los tengas en cuenta en el futuro: no influyen en la evaluación de este trabajo:

- Con la opción `-i` de `wget` podés pasarle directamente el nombre del archivo con el listado de urls. El único caso en el que esto funcionaría y tu solución con `cat` no, sería si la lista de archivos es tan grande que llega al límite de la longitud de un comando bash (porque el cat básicamente resolvería todas las urls una al lado de la otra y las pondría en tu línea de wget).

- Cuando generás el log final, en lugar de hacer `cat myfile.log | grep 'mytext'`, podrías directamente hacer `grep 'mytext' myfile.log`

- En merge.sh, podrías evitar descomprimir y comprimir simplemente haciendo cat sobre los archivos comprimidos: ` cat $1/$3*.fastq.gz > $2/$3.fastq.gz`
